### ISSUE TITLE
Show integrated Terminal in Dap UI

### ISSUE THREAD

**Issue by aditiapratama** [b0o/blender.nvim#4]
Hello, thank you for the wonderful plugin. I use it daily for development.

Anyway, is there a way to integrate the running termina to dap ui just like repl?

The floating window is cool but I like to view the console in bottom split.

Thank you.

**Comment by b0o** [comment]
Hey, glad you're finding it useful! If you close the floating Blender.nvim window by pressing escape, you should be able to show just the DAP REPL with `:DapToggleRepl`.

**Comment by b0o** [comment]
Oh I think I misunderstood your message, you're talking about this buffer, not the repl?

![2024-08-27_02-36-43_region](https://github.com/user-attachments/assets/9c6ab1d3-8ce9-4eec-9013-b40978b70e30)

You're wanting to see the stdout from the Blender process in dapui? I suppose we could add a command to open it in a separate window.

**Comment by aditiapratama** [comment]
> Oh I think I misunderstood your message, you're talking about this buffer, not the repl?
> 
> ![2024-08-27_02-36-43_region](https://private-user-images.githubusercontent.com/21299126/361746561-9c6ab1d3-8ce9-4eec-9013-b40978b70e30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjA5OTAsIm5iZiI6MTcyNDc2MDY5MCwicGF0aCI6Ii8yMTI5OTEyNi8zNjE3NDY1NjEtOWM2YWIxZDMtOGNlOS00ZWVjLTkwMTMtYjQwOTc4YjcwZTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEyMTEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YjZiMDBlOTcwZTA0MWUzMDBhMzJlZGNiODU5ZDdmMzRhODYwOThmYjJiZTZmNTQ2YmVlMmFhYmNjYzM4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k3uPcjXYSHaRPSzj8jIk_1s2D3U7-3-cB4_7gdV95WQ)
> 
> You're wanting to see the stdout from the Blender process? I suppose we could add a command to open it in a separate window.

Yes this is correct, I want to edit while show the log output

**Comment by b0o** [comment]
Sorry for the delay @aditiapratama, I've just added this. Let me know if you have any feedback!

**Comment by aditiapratama** [comment]
wonderful, thank you so much for this feature. Anyway can we change default height in config? Currently it will take half of the screen.

**Comment by b0o** [comment]
Added a config option :+1:

**Comment by aditiapratama** [comment]
Wonderful thank you so much @b0o
